<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email Address' => 'Alamat Email',
    'Full Name' => 'Nama Lengkap',
    'Retype Email Address' => 'Konfirmasi Alamat Email',
    'Retype Password' => 'Konfirmasi Password',
    'Identitas Used' => 'Identitas yang digunakan ',
    'Telephone Number' => 'No Telp. Rumah',
    'Mobile Phone' => 'Nomor Handphone',
    'ID Number' => 'Nomor Identitas',
    'Nationality' => 'Kewarganegaraan',
    'Gender' => 'Jenis Kelamin',
    'Verification Code' => 'Kode verifikasi',

    'Contact' => 'Kontak',
    'Personal' => 'Data Pribadi',
    'Register' => 'Daftar',
    'required' => 'Wajib Diisi',
    'Account' => 'Akun',
    'Choose' => 'Pilih',
    'Creating New Account' => 'Pembuatan Akun Baru',
    'If you have previously registered, please create an account with a different email address.' => 'Apabila Anda telah melakukan pendaftaran sebelumnya, harap membuat akun dengan alamat email yang berbeda.',
    'the username prefix must be a letter, username must not contain spaces.' => 'awalan username harus berupa huruf, username tidak boleh mengandung spasi.',
    'password consists of at least 6 characters, different capital letters and lowercase letters.' => 'password minimal terdiri dari 6 karakter, huruf kapital dan huruf kecil berbeda.',
    'the name corresponds to the identity card, without an academic degree or certification.' => 'nama sesuai dengan kartu identitas, tanpa gelar akademis atau sertifikasi.',
    'Write down your current primary email address used! <strong style="color: red;"> This address will be used to inform all information related to Student Registration </strong>' => 'Tuliskan alamat email utama Anda yang aktif digunakan! <strong style="color: red;"> Alamat ini akan digunakan untuk menginformasikan seluruh informasi terkait PMB (Pendaftaran Mahasiswa Baru) </strong>',
    'Write down your contact phone number with the format + 62xxxxxxxxxxx (your area code without zero). Example: +622518628448 (+62 = code INDONESIA; 251 = kab / city BOGOR; 8628448 = phone number' => 'Tuliskan nomor kontak telpon anda dengan format + 62xxxxxxxxxxx (kode kode daerah anda tanpa angka NOL). Contoh: +622518628448 (+62 = kode INDONESIA; 251 = kab / kota BOGOR; 8628448 = nomor telpon',
    'Enter your mobile phone contact number in + 628xxxxxxxxxxx format (WITHOUT ZERO NUMBER on its mobile number.) Example: +6281212344321 (+62 = INDONESIAN code; 81212344321 = mobile number). <Strong style = "color: red;"> SPs IPB will contact you via this contact number </strong>' => 'Tuliskan nomor kontak telpon mobile Anda dengan format +628xxxxxxxxxxx (TANPA angka NOL pada nomor mobile-nya. Contoh: +6281212344321 (+62 = kode INDONESIA; 81212344321 = nomor mobile). <strong style="color: red;"> SPs IPB akan menghubungi Anda melalui nomor kontak ini </strong>',
    'enter the verification code above.' => 'masukan kode verifikasi di atas.',

    'Male' => 'Laki-Laki',
    'Female' => 'Perempuan',
    'Name' => 'Nama',
    'Degree' => 'Gelar',
    'KTP' => 'KTP',
    'Marital status' => 'Status Perkawinan',
    'NPWP' => 'NPWP',
    'Mother\'s Maiden Name' => 'Nama Gadis Ibu Kandung',
    'Place of Birth' => 'Tempat Lahir',
    'Date of Birth' => 'Tanggal Lahir',
    'Photo Profile' => 'Foto Profile',

    'Districts' => 'Kecamatan',
    'Regency / City' => 'Kabupaten/Kota',
    'Province' => 'Provinsi',
    'Village' => 'Desa',
    'Address' => 'Jalan',
    'Postal code' => 'Kode Pos',

    //menu
    'Complete the Data' => 'Lengkapi Data',
    'Date' => 'Tanggal',
];
