<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\modules\pendaftaran\models\Pendaftaran */
//$username = Yii::$app->user->identity->username;
$link = Yii::$app->urlManager->createAbsoluteUrl(['/pendaftaran/verifikasi/pin/']);
$linkreset = Yii::$app->urlManager->createAbsoluteUrl(['/site/request-password-reset']);

?>
<?php if ($model->orang->negara_id <= 1) {?>
<div class="password-reset">

    <h2>Yth Bapak/Ibu pemilik email <?= $email?></h2>

    <p>Pada tanggal <?= date('d-M-Y') ?> sistem kami menerima permintaan pendaftaran akun untuk Anda.</p>
    <p>
        Nama : <?= $model->orang->nama ?><br>
        Nama Akun : <?= $username ?><br>
        Password : <a href="<?= $linkreset ?>"> Link Reset</a><br>
        Nomor pendaftaran anda : <?= $model->noPendaftaran ?><br>
        <br>
        Gunakan nomor pendaftaran tersebut untuk melakukan pembayaran melalui Bank BNI untuk memperoleh PIN.
        Tata Cara pembayaran silakan klik tautan berikut ini: <a href="http://pmbpasca.ipb.ac.id/formulir/petunjuk_bayar_bni.pdf">Tata cara pembayaran</a>
        <br>
        <br>
        Setelah memperoleh PIN, langkah selanjutnya silahkan verifikasi PIN anda melalui http://pmbpasca.ipb.ac.id atau
        klik tautan berikut ini: <a href="<?= $link ?>"> link verifikasi PIN</a>, lalu lengkapi data sesuai dengan
        tahapan yang tertera.
    </p>
    <p>
        Jika anda tidak merasa melakukan pendaftaran akun pada sistem kami, maka abaikan email ini.
    </p>

    <p>
    Hormat Kami,<br>
    Panitia Penerimaan Mahasiswa Baru <br>
    Sekolah Pascasarjana IPB <br>
    http://pmbpasca.ipb.ac.id <br>
    </p>

    <p>
    Email ini dikirimkan secara otomatis oleh sistem, kami tidak melakukan pengecakan email yang dikirimkan ke email
    ini.
    </p>
    <p>
    Jika ada pertanyaan, silahkan hubungi 0251-8628448
    </p>
</div>

<?php } else {?>
    <div class="password-reset">
        <h2>Dear Mr/ Mrs owner of email <?= $email?></h2>

        <p>On  <?= date('d-M-Y') ?> we have accepted your request to create the admission account at our system:</p>
        <p>
            Name : <?= $model->orang->nama ?><br>
            Account Name : <?= $username ?><br>
            Password : <a href="<?= $linkreset ?>"> Link Reset</a><br>
            Your registration number : <?= $model->noPendaftaran ?><br>
            <br>
            Please wait for confirmation from our administrator to proceed to the next step.
            <br><br>

            <br><br><br>
            Thank you very much.
            <br>

            Best regards,<br>
            New Student Admissions Committee <br>
            Graduate School of IPB <br>
            http://pmbpasca.ipb.ac.id <br>
        </p>

        <p>
            This email is automatically generated by the system, please do not reply to this email.
        </p>
        <p>
            If you have any questions, please contact +62-251-8628448
        </p>
    </div>
<?php }?>