<?php

/* @var $this yii\web\View */
/* @var $model \app\modules\pendaftaran\models\Pendaftaran */
//$username = Yii::$app->user->identity->username;
$link = Yii::$app->urlManager->createAbsoluteUrl(['/pendaftaran/verifikasi/pin/']);
$linkreset = Yii::$app->urlManager->createAbsoluteUrl(['/site/request-password-reset']);
$paket = $model->paketPendaftaran->title;
$program = $model->pendaftaranHasProgramStudis[0];
$sidang = isset($program->prosesSidangs[0]->sidang->id)? $program->prosesSidangs[0]->sidang->paketPendaftaran->title : '';
if(($sidang != '') && ($sidang != $paket)){
	$paket = $sidang;
}
?>
<?php if ($model->orang->negara_id <= 1) {?>
Yth. Sdr. <?= $model->orang->nama?> dengan no pendaftaran <?= $model->noPendaftaran?>

Kami ucapkan terimakasih, dengan ini kami informasikan bahwa data dan berkas yang anda unggah

telah lengkap dan saudara akan diikutsertakan pada Seleksi Calon Pelamar <?= $paket ?>. Selanjutnya, hasil seleksi dapat diakses dengan menggunakan akun saudara pada laman

http://pmbpasca.ipb.ac.id dan juga akan kami umumkan pada laman http://pasca.ipb.ac.id sesuai

dengan jadwal yang ditentukan.

Terimakasih


    Hormat Kami,
    Panitia Penerimaan Mahasiswa Baru
    Sekolah Pascasarjana IPB
    http://pmbpasca.ipb.ac.id



    Email ini dikirimkan secara otomatis oleh sistem, kami tidak melakukan pengecakan email yang dikirimkan ke email
    ini.

    Jika ada pertanyaan, silahkan hubungi 0251-8628448

<?php } else {?>
            Dear Mr/Ms. <?= $model->orang->nama?> with registration number <?= $model->noPendaftaran?>

            Thank you very much.
            We hereby inform you that the data and files you uploaded has completed, and it will be included on the
            Selection process Period 1. Furthermore, the selection results can be accessed by using your account at http://pmbpasca.ipb.ac.id and will be also announced on http://pasca.ipb.ac.id, according to the schedule that will be informed later.

            Terimakasih


            Best regards,
            New Student Admissions Committee
            Graduate School of IPB
            http://pmbpasca.ipb.ac.id

            This email is automatically generated by the system, please do not reply to this email.

            If you have any questions, please contact +62-251-8628448

<?php }?>