<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\modules\pendaftaran\models\Pendaftaran */
//$username = Yii::$app->user->identity->username;
$link = Yii::$app->urlManager->createAbsoluteUrl(['/pendaftaran/verifikasi/pin/']);
$linkreset = Yii::$app->urlManager->createAbsoluteUrl(['/site/request-password-reset']);

?>
<?php if ($model->orang->negara_id > 1) {?>

    Dear Mr/ Mrs <?= $model->orang->nama ?> with registration number <?= $model->noPendaftaran ?>


        Your account has been activated. Please log in with your account to http://pmbpasca.ipb.ac.id
        and complete your personal data by click “Complete the Data” and follow the steps  1-10.


        Thank you very much.


        Best regards,
        New Student Admissions Committee
        Graduate School of IPB
        http://pmbpasca.ipb.ac.id


        This email is automatically generated by the system, please do not reply to this email.

        If you have any questions, please contact +62-251-8628448


<?php } else {?>

    <div class="password-reset">

        <h2>Yth Bapak/Ibu pemilik email <?= $email?></h2>

        <p>Pada tanggal <?= date('d-M-Y') ?> sistem kami menerima permintaan pendaftaran akun untuk Anda.</p>
        <p>
            Nama : <?= $model->orang->nama ?><br>
            Nama Akun : <?= $username ?><br>
            Password : <a href="<?= $linkreset ?>"> Link Reset</a><br>
            Nomor pendaftaran anda : <?= $model->noPendaftaran ?><br>
            <br>
            Gunakan nomor pendaftaran tersebut untuk melakukan pembayaran melalui Bank BNI untuk memperoleh PIN.
            Tata Cara pembayaran silakan klik tautan berikut ini: <a href="http://pmb2017.dev/carabayarbni">Tata cara pembayaran</a>
            <br>
            <br>
            Setelah memperoleh PIN, langkah selanjutnya silahkan verifikasi PIN anda melalui http://pmbpasca.ipb.ac.id atau
            klik tautan berikut ini: <a href="<?= $link ?>"> link verifikasi PIN</a>, lalu lengkapi data sesuai dengan
            tahapan yang tertera.
        </p>
        <p>
            Jika anda tidak merasa melakukan pendaftaran akun pada sistem kami, maka abaikan email ini.
        </p>

        <p>
            Hormat Kami,<br>
            Panitia Penerimaan Mahasiswa Baru <br>
            Sekolah Pascasarjana IPB <br>
            http://pmbpasca.ipb.ac.id <br>
        </p>

        <p>
            Email ini dikirimkan secara otomatis oleh sistem, kami tidak melakukan pengecakan email yang dikirimkan ke email
            ini.
        </p>
        <p>
            Jika ada pertanyaan, silahkan hubungi 0251-8628448
        </p>
    </div>
<?php }?>
